### ISSUE TITLE
Nem működik az egész!!!!!!! (még mindig nem)

### ISSUE THREAD

**Issue by kiszelpeter** [godonypeter/10dFilmekReceptek#3]

**Comment by tcsanad** [comment]
Neked is azt írja haver, hogy "Make sure you configure your 'user.name' and 'user.email' in git." ?

**Comment by hatalyakbalint** [comment]
git config --global user.name "\<név\>"
git config --global user.email "\<email\>"

**Comment by forkoow** [comment]
🐺

**Comment by forkoow** [comment]
🐺
no fox pls

**Comment by G4merSz3mcs1** [comment]
dont 
send help

**Comment by GyrollW** [comment]
### 

> [`_****_`](url)

**Comment by forkoow** [comment]
# tetszik a kocsid roland
## alcim
### al-alcim

**Comment by hatalyakbalint** [comment]
- [x] nem pipa
- [x] pipa
- felsorolás
1. számozás

**Comment by GyrollW** [comment]
### sigma### 

> 

> ### 

> 

> _`_[`or**cock**`](`url`)_`_

**Comment by kiszelpeter** [comment]
Köszi a segítséget csajosok:) nem miattatok oldódott meg
